# https://github.com/meeb/tubesync

version : '3.7'
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: always
    ports:
      - "4848:4848"
    volumes:
      - tubesync_storage:/downloads
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    environment:
      - TZ=Europe/Warsaw
      - GUNICORN_WORKERS=1
    labels:
      my.zone: homeserver
      traefik.enable: true
      traefik.http.routers.cadvisor.rule: Host(`tubesync.${SERVER_DOMAIN}`)
      traefik.http.routers.cadvisor.entrypoints: websecure
      traefik.http.services.cadvisor.loadbalancer.server.port: 4848

volumes:
  tubesync_storage:

networks:
  traefik:
    name: homeserver
    external: true